name: SileroVAD
version: 0.1.0.0
tested-with: GHC == 9.2.8

library:
  source-dirs: src
  c-sources:
    - cbits/**/*
      
data-files:
  - lib/onnxruntime/lib/libonnxruntime.so

tests:
  test:
    main: Main.hs
    source-dirs:
      - src
      - test
    dependencies:
      - tasty
      - tasty-hunit

ghc-options:
  -threaded
  -rtsopts
  -with-rtsopts=-N
  -O2
  -flate-specialise
  -fspecialise-aggressively
  -Wall
  -Wno-name-shadowing
  -Werror

default-extensions:
  - DataKinds
  - DeriveAnyClass
  - DeriveGeneric
  - DerivingStrategies
  - DuplicateRecordFields
  - EmptyDataDecls
  - ExplicitNamespaces
  - FlexibleContexts
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiParamTypeClasses
  - NegativeLiterals
  - NumericUnderscores
  - OverloadedLabels
  - OverloadedStrings
  - OverloadedRecordDot
  - PolyKinds
  - QuasiQuotes
  - RankNTypes
  - ScopedTypeVariables
  - StrictData
  - TemplateHaskell
  - TypeApplications
  - TypeOperators

dependencies:
  - base >= 4.16.4 && < 5
  - unix ^>= 2.8.0.0
  - directory
