name: silero-vad
version: 0.1.0.2
tested-with: GHC == 9.8, GHC == 9.2.8, GHC == 8.10.7
license: MIT
license-file: LICENSE
author: qwbarch
maintainer: qwbarch <qwbarch@gmail.com>
category: Audio, Sound
homepage: https://github.com/qwbarch/silero-vad-hs
bug-reports: https://github.com/qwbarch/silero-vad-hs/issues
extra-doc-files:
  - README.md
  - CHANGELOG.md

synopsis: Voice activity detection powered by SileroVAD.
description: A haskell implentation of SileroVAD, a pre-trained enterprise-grade voice activity detector.

include-dirs:
  - cbits
  - cbits/silero
  - lib/onnxruntime
c-sources: cbits/**/*.c
cc-options: -Wno-unused-result
data-files:
  - lib/onnxruntime/linux-x64/libonnxruntime.so
  - lib/onnxruntime/mac-x64/libonnxruntime.dylib
  - lib/onnxruntime/mac-arm64/libonnxruntime.dylib
  - lib/onnxruntime/windows-x64/onnxruntime.dll
  - lib/silero_vad.onnx
  - lib/jfk.wav

flags:
  build-readme:
    description: "Build the literate haskell README example."
    default: false
    manual: false

library:
  source-dirs: src

executables:
  readme:
    when:
      condition: "!flag(build-readme)"
      buildable: False
    build-tools:  markdown-unlit:markdown-unlit
    main: README.lhs
    source-dirs:
      - .
      - src
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -flate-specialise
      - -fspecialise-aggressively
      - -Wall
      - -Wno-name-shadowing
      - -pgmL markdown-unlit
    dependencies:
      - WAVE ^>= 0.1

tests:
  test:
    main: Main.hs
    source-dirs:
      - src
      - test
    dependencies:
      - tasty > 1 && < 2
      - tasty-hunit > 0.10 && < 1
      - WAVE ^>= 0.1
    ghc-options:
      -threaded
      -rtsopts
      -with-rtsopts=-N
      -flate-specialise
      -fspecialise-aggressively
      -Wall
      -Wno-name-shadowing

default-extensions:
  - DataKinds
  - DeriveAnyClass
  - DeriveGeneric
  - DerivingStrategies
  - DuplicateRecordFields
  - EmptyDataDecls
  - ExplicitNamespaces
  - FlexibleContexts
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiParamTypeClasses
  - NegativeLiterals
  - NumericUnderscores
  - OverloadedLabels
  - OverloadedStrings
  - PolyKinds
  - QuasiQuotes
  - RankNTypes
  - ScopedTypeVariables
  - StrictData
  - TemplateHaskell
  - TypeApplications
  - TypeOperators

dependencies:
  - base >= 4.14.3.0 && < 5
  - vector >= 0.13.0.0 && < 1
  - derive-storable >= 0.3.0.0 && < 1
  - unliftio >= 0.2.20.0 && < 1

when:
  - condition: os(linux) || os(darwin)
    dependencies:
      - unix == 2.*
  - condition: os(windows)
    dependencies:
      - Win32 == 2.*
